import express from 'express';
import { db } from './pkg/database/database.service.js';
import { UsersModule } from './pkg/users/users.module.js';
import { registerHttp, registerErrors } from './pkg/http/http.module.js';
import { healthModule } from './pkg/health/health.module.js';
import { productsModule } from './pkg/products/products.module.js';
import { stockModule } from './pkg/stock/stock.module.js';
import { paymentsModule } from './pkg/payments/payments.module.js';
import { salesModule } from './pkg/sales/sales.module.js';
import { backupModule } from './pkg/backup/backup.module.js';
import { reportsModule } from './pkg/reports/reports.module.js';

export const app = express();
const users = new UsersModule({ db });
registerHttp(app);
app.use('/api', healthModule());
users.register(app);
app.use('/api', users.controller.requireAuth);
app.use('/api', productsModule(users.controller.ownerOnly));
app.use('/api', stockModule(users.controller.ownerOnly));
app.use('/api', paymentsModule(users.controller.ownerOnly));
app.use('/api', salesModule(users.controller.ownerOnly));
app.use('/api', backupModule(users.controller.ownerOnly));
app.use('/api', reportsModule(users.controller.ownerOnly));
registerErrors(app);
